# Generated by Django 5.2.7 on 2025-12-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0002_alter_category_unique_together_and_more"),
        ("inventory", "0006_alter_room_name"),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="institution.category",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="item",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="institution.institution",
                verbose_name="Instituição",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="invoice_key",
            field=models.CharField(
                blank=True, max_length=44, null=True, verbose_name="Nota Fiscal"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="item",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="item",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="inventory.room",
                verbose_name="Sala",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="serial",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Serial"
            ),
        ),
    ]
