# Generated by Django 5.2.7 on 2025-12-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_item_unique_together_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("lost", "Lost"), ("found", "Found")], default="found"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="invoice_key",
            field=models.CharField(
                default=0, max_length=44, verbose_name="Nota Fiscal"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="serial",
            field=models.CharField(default=0, max_length=200, verbose_name="Serial"),
        ),
    ]
