version: "3"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    command: /entrypoint.sh
    depends_on:
      - postgresql

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    ports:
      - 80:80
    depends_on:
      - django

  postgresql:
    image: postgres:16-bullseye
    ports:
      - ${DB_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

volumes:
  static_volume: {}
  media_volume: {}
  data: {}
