version: "3"

services:
  postgresql:
    image: postgres:16-bullseye
    ports:
      - ${DB_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

volumes:
  data:
