# Generated by Django 5.2.7 on 2025-12-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="inventories", to="item.item"
            ),
        ),
    ]
