# Generated by Django 5.2.7 on 2026-01-20 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institution", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="consultors",
            field=models.ManyToManyField(
                related_name="consultories", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="leader_consultor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="responsible",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="inventories", to="inventory.room"
            ),
        ),
    ]
