# Generated by Django 5.2.7 on 2025-12-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
    ]
