# Generated by Django 5.2.7 on 2025-12-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory_consultors_inventory_leader_consultor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('importado', 'Importação Finalizada'), ('conciliado', 'Conciliado')], default='aberto', max_length=30),
        ),
    ]
