# Generated by Django 5.2.7 on 2025-12-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_room_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=set(),
        ),
    ]
