# Generated by Django 5.2.7 on 2025-12-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('Aberto', 'aberto'), ('Encerrado', 'encerrado'), ('Importação Finalizada', 'importado'), ('Conciliado', 'conciliado')], default='Aberto', max_length=30),
        ),
    ]
