# Generated by Django 5.2.7 on 2025-12-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='inventories', to='inventory.room'),
        ),
    ]
