# Generated by Django 5.2.7 on 2026-01-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "conservation_state",
                    models.CharField(
                        choices=[
                            ("new", "Ótimo"),
                            ("good", "Bom"),
                            ("fair", "Usável"),
                            ("poor", "Ruim"),
                            ("unusable", "Inutilizável"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="inventory.inventory",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="item.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Record",
                "verbose_name_plural": "Records",
            },
        ),
    ]
