# Generated by Django 5.2.7 on 2026-01-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='conservation_state',
            field=models.CharField(choices=[('Novo', 'New'), ('Bom', 'Good'), ('Utilizável', 'Fair'), ('Ruim', 'Poor'), ('Inutilizável', 'Unusable')], default='Bom', max_length=30),
        ),
    ]
