# Generated by Django 5.2.7 on 2026-01-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_record_conservation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='conservation_state',
            field=models.IntegerField(choices=[(4, 'Novo'), (3, 'Bom'), (2, 'Utilizável'), (1, 'Ruim'), (0, 'Inutilizável')], default=3),
        ),
    ]
