# Generated by Django 5.2.7 on 2025-12-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="institution",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
