# Generated by Django 5.2.7 on 2025-12-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='institution/logos/'),
        ),
    ]
