# Generated by Django 5.2.7 on 2025-12-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente de Patrimônio'), ('user', 'Consultor de Patrimônio')], default='user', max_length=20),
        ),
    ]
