# Generated by Django 5.2.10 on 2026-01-26 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institution", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("manager", "Gerente de Patrimônio"),
                            ("user", "Consultor de Patrimônio"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="institution.institution",
                    ),
                ),
            ],
        ),
    ]
