# Generated by Django 5.2.7 on 2026-01-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_permission_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
