# Generated by Django 5.2.7 on 2026-01-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_permission_is_active_permission_revoked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='user/photos/'),
        ),
    ]
