# Generated by Django 5.2.7 on 2026-01-14 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='is_active',
        ),
    ]
