# Generated by Django 5.2.7 on 2026-01-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_permission_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
